### ISSUE TITLE
Erro Frequente 

### ISSUE THREAD

**Issue by vinis15** [Hiekki4/Eclipse#57]
Estou com alguns problemas ao iniciar o BOT fiz como dito, mas sempre da esse erro Help plz
![image](https://user-images.githubusercontent.com/77359935/104369853-d52e3880-54fc-11eb-9a3e-2a97961c03ea.png)

**Comment by BONEE4** [comment]
Opa Vini, qual seria seu discord? Por lá podemos bater um papo melhor para resolver esse erro, peço desculpas pela demora.

**Comment by vinis15** [comment]
> Opa Vini, qual seria seu discord? Por lá podemos bater um papo melhor para resolver esse erro, peço desculpas pela demora.

 Meu Discord Vinicius#0870
